// Atlas metadata for public/jardin (generated by scripts/build-jardin-assets.mjs).
// Every atlas is a grid of 8 columns of 256×256 frames at 30 fps.
import type { MowerClip, PlantClip, PlantKind, ZombieClip } from './engine';

export const FRAME_SIZE = 256;
export const ATLAS_COLUMNS = 8;
/** Frame pixels that span one lawn cell; also fixes the zombie walk speed. */
export const FRAME_PX_PER_CELL = 140;
/** The walk art covers 22.2 rig units/s; the engine walks 1.4× faster. */
export const ZOMBIE_WALK_FRAME_RATE = 1.4;

export interface ClipInfo {
  frames: number;
  loop: boolean;
}

export const PLANT_PIVOT = { x: 0.46875, y: 0.9 };
export const ZOMBIE_PIVOT = { x: 0.5, y: 0.9 };
export const MOWER_PIVOT = { x: 0.47, y: 0.9 };

/** 2320×1390 garden: 180 px house strip, 9×5 cells of 200×230, 340 px entry. */
export const BACKGROUND_URL = '/jardin/escenario/jardin.webp';

export const MOWER_CLIPS: Record<MowerClip, ClipInfo> = {
  idle: { frames: 36, loop: true },
  start: { frames: 12, loop: false },
  run: { frames: 24, loop: true },
};

export const PLANT_CLIPS: Record<PlantKind, Partial<Record<PlantClip, ClipInfo>>> = {
  solmiel: { idle: { frames: 72, loop: true }, attack: { frames: 36, loop: false }, spawn: { frames: 36, loop: false } },
  nabu: { idle: { frames: 72, loop: true }, attack: { frames: 36, loop: false }, spawn: { frames: 36, loop: false } },
  cortezon: {
    idle: { frames: 72, loop: true },
    damaged: { frames: 72, loop: true },
    critical: { frames: 72, loop: true },
    spawn: { frames: 36, loop: false },
  },
  granadin: { idle: { frames: 72, loop: true }, attack: { frames: 36, loop: false } },
};

export const ZOMBIE_CLIPS: Record<ZombieClip, ClipInfo> = {
  walk: { frames: 72, loop: true },
  bite: { frames: 36, loop: true },
  fall: { frames: 42, loop: false },
  spawn: { frames: 30, loop: false },
};

export function spriteUrl(character: string, clip: string) {
  return `/jardin/${character}/${clip}.webp`;
}

export function allSpriteUrls(): string[] {
  const urls: string[] = [];
  for (const [kind, clips] of Object.entries(PLANT_CLIPS)) {
    for (const clip of Object.keys(clips)) urls.push(spriteUrl(kind, clip));
    urls.push(spriteUrl(kind, 'portrait'));
  }
  for (const clip of Object.keys(ZOMBIE_CLIPS)) urls.push(spriteUrl('despistado', clip));
  for (const clip of Object.keys(MOWER_CLIPS)) urls.push(spriteUrl('podadora', clip));
  urls.push(BACKGROUND_URL);
  urls.push(spriteUrl('solmiel', 'sun'), spriteUrl('nabu', 'seed'), spriteUrl('granadin', 'burst'));
  return urls;
}

/** Frame to draw for a clip after `elapsed` frames (fractional allowed). */
export function frameIndex(clip: ClipInfo, elapsed: number): number {
  const frame = Math.max(0, Math.floor(elapsed));
  return clip.loop ? frame % clip.frames : Math.min(frame, clip.frames - 1);
}
