// Atlas metadata for public/jardin (generated by scripts/build-jardin-assets.mjs).
// Every atlas is a grid of 8 columns of 256×256 frames at 30 fps.
import type { MowerClip, PlantClip, PlantKind, ProjectileKind, ZombieClip, ZombieKind } from './engine';
import { PLANT_ORDER, ZOMBIES, ZOMBIE_ORDER } from './engine';

export const FRAME_SIZE = 256;
export const ATLAS_COLUMNS = 8;
/** Frame pixels that span one lawn cell; also fixes the zombie walk speed. */
export const FRAME_PX_PER_CELL = 140;

export interface ClipInfo {
  frames: number;
  loop: boolean;
}

export const PLANT_PIVOT = { x: 0.46875, y: 0.9 };
export const ZOMBIE_PIVOT = { x: 0.5, y: 0.9 };
export const MOWER_PIVOT = { x: 0.47, y: 0.9 };

/** 2320×1390 garden: 180 px house strip, 9×5 cells of 200×230, 340 px entry. */
export const BACKGROUND_URL = '/jardin/escenario/jardin.webp';

const clip = (frames: number, loop: boolean): ClipInfo => ({ frames, loop });
const BASE_PLANT = { idle: clip(72, true), attack: clip(36, false), spawn: clip(36, false) };

export const PLANT_CLIPS: Record<PlantKind, Partial<Record<PlantClip, ClipInfo>>> = {
  solmiel: BASE_PLANT,
  nabu: BASE_PLANT,
  mordiseta: BASE_PLANT,
  cardon: BASE_PLANT,
  frigora: BASE_PLANT,
  zarzina: BASE_PLANT,
  cilantro: BASE_PLANT,
  limon: BASE_PLANT,
  jengibron: BASE_PLANT,
  cortezon: { idle: clip(72, true), damaged: clip(72, true), critical: clip(72, true), spawn: clip(36, false) },
  granadin: { idle: clip(72, true), attack: clip(36, false) },
};

const BASE_ZOMBIE: Record<ZombieClip, ClipInfo> = {
  walk: clip(72, true),
  bite: clip(36, true),
  fall: clip(42, false),
  spawn: clip(30, false),
  'armor-break': clip(24, false),
};

/** Clips each zombie has; the special zombies (Ráfago, Brutón) differ. */
export const ZOMBIE_CLIPS: Record<ZombieKind, Partial<Record<ZombieClip, ClipInfo>>> = {
  despistado: { walk: BASE_ZOMBIE.walk, bite: BASE_ZOMBIE.bite, fall: BASE_ZOMBIE.fall, spawn: BASE_ZOMBIE.spawn },
  conero: BASE_ZOMBIE,
  balderon: BASE_ZOMBIE,
  // `walk` is Ráfago's run.
  rafago: { walk: clip(24, true), bite: clip(30, true), fall: clip(36, false), spawn: clip(18, false), 'armor-break': clip(18, false) },
  // `bite` is Brutón's punch, repeated while it smashes a plant.
  bruton: { walk: clip(72, true), bite: clip(42, true), fall: clip(36, false), spawn: clip(18, false) },
};

/** Drawing scale per zombie: Brutón is a giant. */
export const ZOMBIE_SCALE: Partial<Record<ZombieKind, number>> = { bruton: 1.25 };

/** Clips that also exist without armour (`sin-` atlases). */
const UNARMORED_CLIPS: ZombieClip[] = ['walk', 'bite', 'fall'];

export const MOWER_CLIPS: Record<MowerClip, ClipInfo> = {
  idle: clip(36, true),
  start: clip(12, false),
  run: clip(24, true),
};

export const PROJECTILE_IMAGES: Record<ProjectileKind, { url: string; size: number; y: number }> = {
  seed: { url: '/jardin/nabu/seed.webp', size: 0.42, y: 0.42 },
  spore: { url: '/jardin/mordiseta/spore.webp', size: 0.4, y: 0.62 },
  spine: { url: '/jardin/cardon/spine.webp', size: 0.5, y: 0.32 },
  frost: { url: '/jardin/frigora/frost.webp', size: 0.42, y: 0.6 },
  aroma: { url: '/jardin/cilantro/aroma.webp', size: 0.5, y: 0.45 },
  acid: { url: '/jardin/limon/acid.webp', size: 0.38, y: 0.62 },
};

export function spriteUrl(character: string, name: string) {
  return `/jardin/${character}/${name}.webp`;
}

/** Atlas file for a zombie clip; armoured kinds switch art once the armour falls. */
export function zombieSpriteName(kind: ZombieKind, clipName: ZombieClip, armored: boolean) {
  if (ZOMBIES[kind].armor > 0 && !armored && UNARMORED_CLIPS.includes(clipName)) return `sin-${clipName}`;
  return clipName;
}

export function plantSpriteUrls(kind: PlantKind): string[] {
  return Object.keys(PLANT_CLIPS[kind]).map((name) => spriteUrl(kind, name));
}

export function zombieSpriteUrls(kind: ZombieKind): string[] {
  const names: string[] = Object.keys(ZOMBIE_CLIPS[kind]);
  if (ZOMBIES[kind].armor > 0) names.push(...UNARMORED_CLIPS.map((name) => `sin-${name}`));
  return names.map((name) => spriteUrl(kind, name));
}

/** Needed before the board can be shown: scenery, cards and the basic zombie. */
export function criticalUrls(): string[] {
  return [
    BACKGROUND_URL,
    ...PLANT_ORDER.map((kind) => spriteUrl(kind, 'portrait')),
    ...ZOMBIE_ORDER.map((kind) => spriteUrl(kind, 'portrait')),
    ...Object.keys(MOWER_CLIPS).map((name) => spriteUrl('podadora', name)),
    ...zombieSpriteUrls('despistado'),
    spriteUrl('solmiel', 'sun'),
  ];
}

/** Everything else, streamed in the background after the board is up. */
export function deferredUrls(): string[] {
  return [
    ...Object.values(PROJECTILE_IMAGES).map((image) => image.url),
    spriteUrl('granadin', 'burst'),
    ...PLANT_ORDER.flatMap(plantSpriteUrls),
    spriteUrl('jengibron', 'impact'),
    ...ZOMBIE_ORDER.filter((kind) => kind !== 'despistado').flatMap(zombieSpriteUrls),
  ];
}

/** Frame to draw for a clip after `elapsed` frames (fractional allowed). */
export function frameIndex(info: ClipInfo, elapsed: number): number {
  const frame = Math.max(0, Math.floor(elapsed));
  return info.loop ? frame % info.frames : Math.min(frame, info.frames - 1);
}
